#!/bin/bash

NAME="notification-configurator"
DOMAIN="exposedcat"

SLUG="$NAME@$DOMAIN"
ARCHIVE="$SLUG.shell-extension.zip"
EXTENSIONS="/home/$USER/.local/share/gnome-shell/extensions"

pack() {
	gnome-extensions pack --podir=po dist --extra-source=shell --extra-source=utils  --extra-source=managers --force
}

build() {
  npx tsc
  cp -r metadata.json schemas po dist
  glib-compile-schemas ./dist/schemas
}

inject() {
  mkdir -p "$EXTENSIONS"
  rm -rf "${EXTENSIONS:?}/$SLUG"
  unzip $ARCHIVE -d "$EXTENSIONS/$SLUG"
  glib-compile-schemas "$EXTENSIONS/$SLUG/schemas"
}

case $1 in
clean)
  rm -rf dist node_modules $ARCHIVE
  ;;
build)
  build
  ;;
pack)
	build
	pack
  ;;
inject)
	pack
	inject
  ;;
translate)
  build
	./scripts/update-pot.sh
  ;;
uninstall)
  rm -rf "${EXTENSIONS:?}/$SLUG"
  ;;
dev)
	build
	pack
  inject
  dbus-run-session -- gnome-shell --nested --wayland
  ;;
*)
  echo "Unknown command '$1'"
  ;;
esac
