name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y glib2.0-dev libglib2.0-dev-bin

    - name: Build extension
      run: npm run build

    - name: Package extension
      run: npm run pack

    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: gnome-shell-extension-package
        path: notification-configurator.zip
        retention-days: 30

    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./notification-configurator.zip
        asset_name: notification-configurator-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
